### ISSUE TITLE
获取token的地址能否更新一下

### ISSUE THREAD

**Issue by scpzc** [royalrick/weapp#105]
现在包里面的是旧的地址 https://api.weixin.qq.com/cgi-bin/token   这个地址每天获取次数多了就报错 wechat server error: code[45009] msg[reach max api daily quota limit, could get access_token by getStableAccessToken, more details at https://mmbizurl.cn/s/JtxxFh33r rid: 654e20fe-255cb46d-7fc880f7]       麻烦更新成这个呢  https://api.weixin.qq.com/cgi-bin/stable_token

**Comment by scpzc** [comment]
https://developers.weixin.qq.com/doc/offiaccount/Basic_Information/getStableAccessToken.html

**Comment by royalrick** [comment]
好的，我新增加一个接口

**Comment by royalrick** [comment]
之前的接口需要自行缓存；

**Comment by royalrick** [comment]
已经在 3.8 中增加了这些功能

**Comment by scpzc** [comment]
> 已经在 3.8 中增加了这些功能

看到了，多谢。但是有个问题，像这样的接口sdk.GenerateURLScheme 怎么方便直接切换成使用stableAccessToken呢？还是要自定义获取token，再传进去吗？

**Comment by royalrick** [comment]
很久没关注小程序了，看了下文档，意思是现在可以统一用 stable acess token 替换之间的唯一 access token 了对吧？如果是这样的话我就全部切换到 stable acess token

**Comment by royalrick** [comment]
已经更新
