### ISSUE TITLE
SubscribeMessage 一些错误

### ISSUE THREAD

**Issue by JiajunDou** [royalrick/weapp#62]
```
// SubscribeMessage 订阅消息
type SubscribeMessage struct {
	ToUser           string           `json:"touser"`
	TemplateID       string           `json:"template_id"`
	Page             string           `json:"page,omitempty"`
	MiniprogramState MiniprogramState `json:"miniprogram_state,omitempty"`
	Data             string           `json:"data"`
}
```
这里的Data是string 但是下面的是SubscribeMessageData？
```
sender := weapp.SubscribeMessage{
    ToUser:     mpOpenID,
    TemplateID: "template-id",
    Page:       "mock/page/path",
    MiniprogramState:cli.MiniprogramStateDeveloper, // 或者: "developer"
    Data:cli.SubscribeMessageData{
        "first-key": {
            Value: "value",
        },
        "second-key": {
            Value: "value",
        },
    },
}
```
cli.MiniprogramStateDeveloper 这个引用的路径不正确 这里的是weapp.MiniprogramStateDeveloper

**Comment by JiajunDou** [comment]
```
type SubscribeMessage struct {
	ToUser           string                 `json:"touser"`
	TemplateID       string                 `json:"template_id"`
	Page             string                 `json:"page,omitempty"`
	MiniprogramState MiniprogramState       `json:"miniprogram_state,omitempty"`
	Data             map[string]interface{} `json:"data"`
}
```
这里应该是 map[string]interface{}

**Comment by medivhzhan** [comment]
谢谢指正 应该是 `subscribemessage.MiniprogramStateDeveloper`

**Comment by medivhzhan** [comment]
> ```
> type SubscribeMessage struct {
> 	ToUser           string                 `json:"touser"`
> 	TemplateID       string                 `json:"template_id"`
> 	Page             string                 `json:"page,omitempty"`
> 	MiniprogramState MiniprogramState       `json:"miniprogram_state,omitempty"`
> 	Data             map[string]interface{} `json:"data"`
> }
> ```
> 
> 这里应该是 map[string]interface{}

v2 用的是map，但是在实际应用中不是很好转换和使用，所以考虑在v3使用微信接口原生的string类型；

**Comment by medivhzhan** [comment]
> ```
> type SubscribeMessage struct {
> 	ToUser           string                 `json:"touser"`
> 	TemplateID       string                 `json:"template_id"`
> 	Page             string                 `json:"page,omitempty"`
> 	MiniprogramState MiniprogramState       `json:"miniprogram_state,omitempty"`
> 	Data             map[string]interface{} `json:"data"`
> }
> ```
> 
> 这里应该是 map[string]interface{}

v2 用的是map，但是在实际应用中不是很好转换和使用，所以考虑在v3使用微信接口原生的string类型；

**Comment by JiajunDou** [comment]
package weapp

weapp.MiniprogramStateDeveloper

subscribemessage.MiniprogramStateDeveloper IDE会直接报错

**Comment by medivhzhan** [comment]
<img width="1052" alt="截屏2021-09-21 上午7 57 55" src="https://user-images.githubusercontent.com/16298099/134092173-ec0ae349-d797-4780-b2c6-224dea77aea2.png">
试了下没问题呢

**Comment by JiajunDou** [comment]
引用import weapp开发 按照文档会报错

**Comment by medivhzhan** [comment]
看下具体的错误是啥呢

VENI VIDI VICI

**Comment by codingcn** [comment]
> 看下具体的错误是啥呢 VENI VIDI VICI
> […](#)
> 在 2021年9月21日，上午8:45，JiajunDou ***@***.***> 写道： ﻿ 引用import weapp开发 按照文档会报错 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

订阅消息data为string，我这边一直提示参数错误，没找出是什么原因

这是我的代码
```
res, err1 := miniapp.MiniAppCli.SendSubscribeMsg(&weapp.SubscribeMessage{
	ToUser:           "o4Q0Y5Xt1Kx0xp3hIw-luS1xHGO0",
	TemplateID:       "p2Byu2vTmAPiuYo_Kwrgg6xr9j_2QtssGHQ1uX2IT7Y",
	Page:             "pages/index/index",
	MiniprogramState: weapp.MiniprogramStateDeveloper,
	Data:             `{"name1":{"value":"11111"},"time3":{"value":"3333"},"thing7":{"value":"7777"}}`,
})
fmt.Println("订阅消息响应", res,err1)
```
下面是报错`data.name1.value is emtpy`
```
2021/10/15 16:46:18 [info] request params: &{ToUser:o4Q0Y5Xt1Kx0xp3hIw-luS1xHGO0 TemplateID:p2Byu2vTmAPiuYo_Kwrgg6xr9j_2QtssGHQ1uX2IT7Y Page:pages/index/index MiniprogramState:developer Data:{"name1":{"value":"11111"},"time3":{"value":"3333"},"thing7":{"value":"7777"}}}

订阅消息响应 &{47003 argument invalid! data.name1.value is emtpy rid: 61693fdb-4e573d1c-6310270b} <nil>
```

**Comment by codingcn** [comment]
@royalrick 
我自己把data改成map类型，结果发送成功了。

```
// SubscribeMessage 订阅消息
type SubscribeMessage struct {
	ToUser           string           `json:"touser"`
	TemplateID       string           `json:"template_id"`
	Page             string           `json:"page,omitempty"`
	MiniprogramState MiniprogramState `json:"miniprogram_state,omitempty"`
	Data             map[string]interface{}       `json:"data"`
}
```

**Comment by royalrick** [comment]
已经修复，谢谢：）

**Comment by puppet-king** [comment]
SubscribeMessage 结构还是 string， 在 json 编码的时候会加上转移符，仍然无法使用撒

**Comment by puppet-king** [comment]
> SubscribeMessage 结构还是 string， 在 json 编码的时候会加上转移符，仍然无法使用撒

看到另外一个 issues 了， 打扰了
