### ISSUE TITLE
订阅消息有单条的，不全都是数组

### ISSUE THREAD

**Issue by JiajunDou** [royalrick/weapp#63]
{
    "ToUserName": "gh_123456789abc",
    "FromUserName": "o7esq5PHRGBQYmeNyfG064wEFVpQ",
    "CreateTime": "1620963428",
    "MsgType": "event",
    "Event": "subscribe_msg_sent_event",
    "SubscribeMsgSentEvent": {
      "List": {
        "TemplateId": "BEwX0BO-T3MqK3Uc5oTU3CGBqzjpndk2jzUf7VfExd8",
        "MsgID": "1864323726461255680",
        "ErrorCode": "0",
        "ErrorStatus": "success"
          }
      }
}

然后源码里面是绑定一个数组，真的是伤不起

**Comment by medivhzhan** [comment]
这个事件还未录入
