### ISSUE TITLE
订阅消息data结构体

### ISSUE THREAD

**Issue by hxnets** [royalrick/weapp#68]
订阅消息的data是不是忘记从v2版本带过来了？要求类型是string，我咋转换都不行，没办法把v2的 SubscribeMessageData 带过来了，是不是请求的时候会做一次 json导致的 string处理异常？

因为如果传string 结构怎么滴都不对

如果是string就是这样
![image](https://user-images.githubusercontent.com/32917172/139581553-6ed6bac6-be02-4b85-b3a9-e28ef45164b3.png)

下面是v2版本的
![image](https://user-images.githubusercontent.com/32917172/139581537-cf997cbd-4245-4a9a-8307-0c442f85d272.png)

**Comment by hxnets** [comment]
我的错 改为 NewSubscribeMessage 就好了 我用的老方法

**Comment by royalrick** [comment]
好的👌
