### ISSUE TITLE
v1需要添加profit_sharing这个字段，

### ISSUE THREAD

**Issue by cobain** [royalrick/weapp#91]
v1需要在下单的时候添加profit_sharing这个字段，该字段本身可选，值只有Y和N
![image](https://user-images.githubusercontent.com/2162996/222326191-63a73a1a-fdad-4348-a06e-e560ca2b0224.png)

**Comment by cobain** [comment]
比较着急，我自己发了一个pr，麻烦看看。

**Comment by royalrick** [comment]
v1.5.2发布了

**Comment by cobain** [comment]
感谢

**Comment by cobain** [comment]
加的有点问题，我重新发个pr

**Comment by cobain** [comment]
抱歉，今天有点着急，没仔细看，刚才重新改了。pr提交了

**Comment by cobain** [comment]
还是弄个群方便一点。😂。

**Comment by royalrick** [comment]
OK了
